name: Dev Continuous Delivery Workflow 
on:
  push:
    branches: [ dev ]
jobs:
  test-environment-infrastructure:
    name: Create Environment 
    uses: ./.github/workflows/create-cluster.yaml
    secrets: inherit